name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ git: https://JongeunKeum@github.com/ on DESKTOP-67NSIH2 at 03-9-2020 01:01 }}
        with:
          USERNAME: ${{ github.repository_owner }}
